package interfaceGrafica.Empresas;

import gerTarefas.gerInterface.Constantes.TipoFormulario;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.EDITAR;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.FILTRAR;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.INSERIR;
import gerTarefas.gerInterface.comum.CustomFormularioInterface;
import gerTarefas.gerInterface.comum.InterfGerenciadorInterface;
import gerTarefas.gerInterface.comum.ValidaCampoForm;
import modelo.Empresa;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author João Vitor
 */
public class FormularioEmpresa extends javax.swing.JDialog implements CustomFormularioInterface<Empresa> {
    private Empresa empresa;
    private TipoFormulario tipo;
    InterfGerenciadorInterface gerenciador;
    
    /**
     * Creates new form CadastroEmpresa
     * @param parent
     * @param modal
     * @param gerenciador
     */
    public FormularioEmpresa(java.awt.Frame parent, boolean modal, InterfGerenciadorInterface gerenciador) {
        super(parent, modal);
        this.tipo = INSERIR;
        this.gerenciador = gerenciador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloModal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        razaoSocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cnpjEmpresa = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        telefoneEmpresa = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        nomeContatoEmpresa = new javax.swing.JTextField();
        emailEmpresa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeFantasia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloModal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloModal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloModal.setText("Nova Empresa");
        tituloModal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setText("Razão social:");

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("CNPJ:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 244, 24));

        try {
            cnpjEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(cnpjEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 30));

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Telefone:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 20));

        try {
            telefoneEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel8.add(telefoneEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 30));

        jPanel6.add(jPanel8);

        jLabel11.setText("Nome de contato:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Concluir");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel12.setText("E-mail:");

        jLabel1.setText("Nome fantasia:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(razaoSocial)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeContatoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(emailEmpresa)))
                    .addComponent(nomeFantasia)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeContatoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(tituloModal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloModal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        closeModal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        gerenciador.concluir();
    }//GEN-LAST:event_btnCadastrarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JFormattedTextField cnpjEmpresa;
    private javax.swing.JTextField emailEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nomeContatoEmpresa;
    private javax.swing.JTextField nomeFantasia;
    private javax.swing.JTextField razaoSocial;
    private javax.swing.JFormattedTextField telefoneEmpresa;
    private javax.swing.JLabel tituloModal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void abrirModalEdicao(Empresa empresa) {
        this.empresa = empresa;
        this.tipo = EDITAR;
        alterarTituloModal();
        
        razaoSocial.setText(empresa.getRazaoSocial());
        nomeFantasia.setText(empresa.getNomeFantasia());
        cnpjEmpresa.setText(empresa.getCnpj());
        telefoneEmpresa.setText(empresa.getTelefone());
        nomeContatoEmpresa.setText(empresa.getNomeContato());
        emailEmpresa.setText(empresa.getEmail());
        
        this.setVisible(true);
    }

    @Override
    public void abrirModalCriacao() {
        this.tipo = INSERIR;
        alterarTituloModal();
        this.setVisible(true);
    }
    
    @Override
    public void abrirModalFiltragem() {
        this.tipo = FILTRAR;
        alterarTituloModal();
        this.setVisible(true);
    }

    @Override
    public void alterarTituloModal() {
        String titulo = "";
        if(null != this.tipo) switch (this.tipo) {
            case INSERIR:
                titulo = "Nova Empresa";
                break;
            case EDITAR:
                titulo = "Editar Empresa";
                break;
            case FILTRAR:
                titulo = "Filtrar Empresa";
                break;
            default:
                break;
        }
        
        tituloModal.setText(titulo);
    }

    @Override
    public void closeModal() {
        this.dispose();
    }

    @Override
    public Empresa toObject() {
        String razao = ValidaCampoForm.getTexto(razaoSocial, this, "Digite uma razão social válida");
        String nomeF = ValidaCampoForm.getTexto(nomeFantasia, this, "Digite um nome fantasia válido");
        String cnpj = ValidaCampoForm.getCnpj(cnpjEmpresa, this, "Digite um CNPJ válido");
        String telefone = ValidaCampoForm.getTelefone(telefoneEmpresa, this, "Digite um telefone válido");
        String nomeContato = ValidaCampoForm.getTexto(nomeContatoEmpresa, this, "Digite um nome de contato válido");
        String email = ValidaCampoForm.getEmail(emailEmpresa, this, "Digite um E-mail válido");
        
        if(razao.equals("") || nomeF.equals("") || cnpj.equals("") || telefone.equals("") || nomeContato.equals("") || email.equals("")){
            return null;
        }
        
        Empresa emp;
        if(this.tipo == EDITAR) emp = new Empresa(empresa.getCodigo(), razao, nomeF, cnpj,email, telefone, nomeContato);
        else emp = new Empresa(empresa.getCodigo(), razao, nomeF, cnpj,email, telefone, nomeContato);
        return emp;
    }

    @Override
    public TipoFormulario getTipo() {
        return this.tipo;
    }

    @Override
    public void limparCampos() {
        razaoSocial.setText("");
        nomeFantasia.setText("");
        cnpjEmpresa.setText("");
        telefoneEmpresa.setText("");
        nomeContatoEmpresa.setText("");
        emailEmpresa.setText("");
    }
}
