package interfaceGrafica.Formularios;

import gerTarefas.gerInterface.Constantes.Coordenadoria;
import gerTarefas.gerInterface.Constantes.TipoFormulario;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.EDITAR;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.FILTRAR;
import static gerTarefas.gerInterface.Constantes.TipoFormulario.INSERIR;
import gerTarefas.gerInterface.GerenciadorProfessor;
import gerTarefas.gerInterface.comum.AlertaErro;
import gerTarefas.gerInterface.comum.CustomFormularioInterface;
import gerTarefas.gerInterface.comum.ValidaCampoForm;
import modelo.Professor;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author João Vitor
 */
public class FormularioProfessor extends javax.swing.JDialog implements CustomFormularioInterface<Professor>{
    private Professor professorSelecionado;
    private TipoFormulario tipo;
    private final GerenciadorProfessor gerenciador;
    
    /**
     * Creates new form CadastroProfessor
     * @param parent
     * @param modal
     * @param gerenciador
     */
    public FormularioProfessor(java.awt.Frame parent, boolean modal, GerenciadorProfessor gerenciador) {
        super(parent, modal);
        this.tipo = INSERIR;
        this.gerenciador = gerenciador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloModal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nomeProfessor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        siapeProfessor = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        coordenadoriaSelect = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        emailProfessor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tituloModal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloModal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloModal.setText("Novo Professor");
        tituloModal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setText("Nome do professor:");

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Siape:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 244, 24));

        siapeProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                siapeProfessorKeyReleased(evt);
            }
        });
        jPanel7.add(siapeProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 30));

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Coordenadoria");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 20));

        jPanel8.add(coordenadoriaSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 30));

        jPanel6.add(jPanel8);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Concluir");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel12.setText("E-mail:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeProfessor)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(emailProfessor))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(tituloModal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloModal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        gerenciador.fecharModal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        gerenciador.concluir();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        coordenadoriaSelect.removeAllItems();
        for(Coordenadoria item : Coordenadoria.values()){
            coordenadoriaSelect.addItem(item);
        }
    }//GEN-LAST:event_formComponentShown

    private void siapeProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siapeProfessorKeyReleased
        String siape = this.siapeProfessor.getText();
        if(siape.length() > 9){
            siape = siape.substring(0, 9);
            this.siapeProfessor.setText(siape);
        }
    }//GEN-LAST:event_siapeProfessorKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Object> coordenadoriaSelect;
    private javax.swing.JTextField emailProfessor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nomeProfessor;
    private javax.swing.JTextField siapeProfessor;
    private javax.swing.JLabel tituloModal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEntidadeSelecionada(Professor entidade) {
        this.professorSelecionado = entidade;
    }

    @Override
    public void setCamposFormulario(Professor professor) {
        nomeProfessor.setText(professor.getNome());
        siapeProfessor.setText(professor.getSiape());
        coordenadoriaSelect.setSelectedItem(professor.getCoordenadoria());
        emailProfessor.setText(professor.getEmail());
    }
    
    @Override
    public void alterarTituloModal() {
        String titulo = "";
        if(null != this.tipo) switch (this.tipo) {
            case INSERIR:
                titulo = "Novo Professor";
                break;
            case EDITAR:
                titulo = "Editar Professor";
                break;
            case FILTRAR:
                titulo = "Filtrar Professor";
                break;
            default:
                break;
        }
        
        tituloModal.setText(titulo);
    }

    @Override
    public void closeModal() {
        this.dispose();
    }
    
    @Override
    public void showModal(){
        this.setVisible(true);
    }
    
    private Professor getProfessor(){
        return new Professor(
                siapeProfessor.getText(),
                nomeProfessor.getText(),
                (Coordenadoria) coordenadoriaSelect.getSelectedItem(),
                emailProfessor.getText()
        );
    }

    @Override
    public Professor toObject() {
        if(this.tipo == FILTRAR) return getProfessor();
        
        String nome = ValidaCampoForm.getTexto(nomeProfessor, this, "Insira um nome válido");
        String siape = ValidaCampoForm.getTexto(siapeProfessor, this, "Insira um siape válido");
        Coordenadoria coordenadoria = (Coordenadoria) ValidaCampoForm.getValue(coordenadoriaSelect, this);
        String email = ValidaCampoForm.getTexto(emailProfessor, this, "Insira um e-mail válido");
        
        if(nome.equals("") || siape.equals("") || email.equals("")){
            return null;
        } else if(siape.length() < 9) {
            AlertaErro.showErro(this, "Siape deve conter 9 digitos");
            return null;
        }
        
        Professor prof;
        if(this.tipo == EDITAR) prof = new Professor(professorSelecionado.getCodigo(), siape, nome, coordenadoria, email);
        else prof = new Professor(siape, nome, coordenadoria, email);
        return prof;
    }

    @Override
    public TipoFormulario getTipo() {
        return this.tipo;
    }

    @Override
    public void setTipo(TipoFormulario tipo) {
        this.tipo = tipo;
    }

    @Override
    public void limparCampos() {
        nomeProfessor.setText("");
        siapeProfessor.setText("");
        coordenadoriaSelect.setSelectedIndex(0);
        emailProfessor.setText("");
    }
}
