package interfaceGrafica;

import gerTarefas.gerInterface.GerenciadorInterface;
import modelo.Projeto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author João Vitor
 */
public class MainWindow extends javax.swing.JFrame {
    private final GerenciadorInterface gerenciadorInterface;
    private boolean carregou = false;

    
    /**
     * Creates new form MainWindow
     * @param gerenciadorInterface
     */
    public MainWindow(GerenciadorInterface gerenciadorInterface) {
        this.gerenciadorInterface = gerenciadorInterface;
        
        initComponents();
    }
    
    public void iniciarTabelas(){
        this.gerenciadorInterface.getAluno().setTabela(jtbListaAlunos);
        this.gerenciadorInterface.getEmpresa().setTabela(jtbListaEmpresas);
        this.gerenciadorInterface.getProfessor().setTabela(jtbListaProfessores);
        this.gerenciadorInterface.getProjeto().setTabela(jtbListaProjetos);
        
        this.gerenciadorInterface.getProjeto().listar();
        this.carregou = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnNovoProjeto = new javax.swing.JButton();
        listagemProjetos = new javax.swing.JScrollPane();
        jtbListaProjetos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        excluirProjeto = new javax.swing.JButton();
        btnEditarProjeto = new javax.swing.JButton();
        btnAbrirProjeto = new javax.swing.JButton();
        btnFiltrarProjetos = new javax.swing.JButton();
        limparFiltroProjetos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNovoAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListaAlunos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        excluirAluno = new javax.swing.JButton();
        btnEditarAluno = new javax.swing.JButton();
        btnFiltrarAlunos = new javax.swing.JButton();
        limparFiltroAlunos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNovoProfessor = new javax.swing.JButton();
        containerprofessores = new javax.swing.JScrollPane();
        jtbListaProfessores = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        excluirProfessor = new javax.swing.JButton();
        btnEditarProfessor = new javax.swing.JButton();
        btnFiltrarProfessores = new javax.swing.JButton();
        limparFiltroProfessores = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNovaEmpresa = new javax.swing.JButton();
        containerempresas = new javax.swing.JScrollPane();
        jtbListaEmpresas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        excluirEmpresa = new javax.swing.JButton();
        btnEditarEmpresa = new javax.swing.JButton();
        btnFiltrarEmpresas = new javax.swing.JButton();
        limparFiltroEmpresas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNovoProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/add.png"))); // NOI18N
        btnNovoProjeto.setText("Novo projeto");
        btnNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jtbListaProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listagemProjetos.setViewportView(jtbListaProjetos);

        jPanel1.add(listagemProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 280));

        excluirProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/remove.png"))); // NOI18N
        excluirProjeto.setText("Excluir");
        excluirProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProjetoActionPerformed(evt);
            }
        });

        btnEditarProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/botao-editar.png"))); // NOI18N
        btnEditarProjeto.setText("Editar");
        btnEditarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProjetoActionPerformed(evt);
            }
        });

        btnAbrirProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/detalhes.png"))); // NOI18N
        btnAbrirProjeto.setText("Abrir Projeto");
        btnAbrirProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirProjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(btnAbrirProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btnEditarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrirProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnEditarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 800, -1));

        btnFiltrarProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/search.png"))); // NOI18N
        btnFiltrarProjetos.setText("Filtrar resultados");
        btnFiltrarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarProjetosActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrarProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 40));

        limparFiltroProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/clear-filter.png"))); // NOI18N
        limparFiltroProjetos.setText("Limpar filtros");
        limparFiltroProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFiltroProjetosActionPerformed(evt);
            }
        });
        jPanel1.add(limparFiltroProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 40));

        jTabbedPane1.addTab("Projetos", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        btnNovoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/Imagens/add.png"))); // NOI18N
        btnNovoAluno.setText("Novo aluno");
        btnNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlunoActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jtbListaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbListaAlunos);

        excluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/remove.png"))); // NOI18N
        excluirAluno.setText("Excluir");
        excluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAlunoActionPerformed(evt);
            }
        });

        btnEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/botao-editar.png"))); // NOI18N
        btnEditarAluno.setText("Editar");
        btnEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(btnEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(excluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnFiltrarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/search.png"))); // NOI18N
        btnFiltrarAlunos.setText("Filtrar resultados");
        btnFiltrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarAlunosActionPerformed(evt);
            }
        });

        limparFiltroAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/clear-filter.png"))); // NOI18N
        limparFiltroAlunos.setText("Limpar filtros");
        limparFiltroAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFiltroAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnFiltrarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limparFiltroAlunos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparFiltroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFiltrarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Alunos", jPanel2);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        btnNovoProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/Imagens/add.png"))); // NOI18N
        btnNovoProfessor.setText("Novo professor");
        btnNovoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProfessorActionPerformed(evt);
            }
        });

        containerprofessores.setBorder(null);

        jtbListaProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        containerprofessores.setViewportView(jtbListaProfessores);

        excluirProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/remove.png"))); // NOI18N
        excluirProfessor.setText("Excluir");
        excluirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProfessorActionPerformed(evt);
            }
        });

        btnEditarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/botao-editar.png"))); // NOI18N
        btnEditarProfessor.setText("Editar");
        btnEditarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(btnEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(excluirProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnFiltrarProfessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/search.png"))); // NOI18N
        btnFiltrarProfessores.setText("Filtrar resultados");
        btnFiltrarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarProfessoresActionPerformed(evt);
            }
        });

        limparFiltroProfessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/clear-filter.png"))); // NOI18N
        limparFiltroProfessores.setText("Limpar filtros");
        limparFiltroProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFiltroProfessoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparFiltroProfessores)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(containerprofessores)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrarProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limparFiltroProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(containerprofessores, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Professores", jPanel3);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        btnNovaEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/Imagens/add.png"))); // NOI18N
        btnNovaEmpresa.setText("Nova Empresa");
        btnNovaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaEmpresaActionPerformed(evt);
            }
        });

        containerempresas.setBorder(null);

        jtbListaEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        containerempresas.setViewportView(jtbListaEmpresas);

        excluirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/remove.png"))); // NOI18N
        excluirEmpresa.setText("Excluir");
        excluirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEmpresaActionPerformed(evt);
            }
        });

        btnEditarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/botao-editar.png"))); // NOI18N
        btnEditarEmpresa.setText("Editar");
        btnEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(btnEditarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(excluirEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnFiltrarEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/search.png"))); // NOI18N
        btnFiltrarEmpresas.setText("Filtrar resultados");
        btnFiltrarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarEmpresasActionPerformed(evt);
            }
        });

        limparFiltroEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/imagens/clear-filter.png"))); // NOI18N
        limparFiltroEmpresas.setText("Limpar filtros");
        limparFiltroEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFiltroEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerempresas)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNovaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrarEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(limparFiltroEmpresas))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNovaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(limparFiltroEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltrarEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(containerempresas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Empresas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProjetoActionPerformed
        this.gerenciadorInterface.getProjeto().abrirModalCriacao();
        
    }//GEN-LAST:event_btnNovoProjetoActionPerformed

    private void btnNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlunoActionPerformed
        gerenciadorInterface.getAluno().abrirModalCriacao();
    }//GEN-LAST:event_btnNovoAlunoActionPerformed

    private void btnNovoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProfessorActionPerformed
        this.gerenciadorInterface.getProfessor().abrirModalCriacao();
    }//GEN-LAST:event_btnNovoProfessorActionPerformed

    private void btnNovaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaEmpresaActionPerformed
        this.gerenciadorInterface.getEmpresa().abrirModalCriacao();
    }//GEN-LAST:event_btnNovaEmpresaActionPerformed

    private void btnFiltrarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarProjetosActionPerformed
        this.gerenciadorInterface.getProjeto().abrirModalFiltragem();
    }//GEN-LAST:event_btnFiltrarProjetosActionPerformed

    private void btnFiltrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarAlunosActionPerformed
        gerenciadorInterface.getAluno().abrirModalFiltragem();
    }//GEN-LAST:event_btnFiltrarAlunosActionPerformed

    private void btnFiltrarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarProfessoresActionPerformed
        this.gerenciadorInterface.getProfessor().abrirModalFiltragem();
    }//GEN-LAST:event_btnFiltrarProfessoresActionPerformed

    private void btnFiltrarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarEmpresasActionPerformed
        this.gerenciadorInterface.getEmpresa().abrirModalFiltragem();
    }//GEN-LAST:event_btnFiltrarEmpresasActionPerformed

    private void btnEditarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProjetoActionPerformed
        this.gerenciadorInterface.getProjeto().abrirModalEdicao();
    }//GEN-LAST:event_btnEditarProjetoActionPerformed

    private void btnEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlunoActionPerformed
        gerenciadorInterface.getAluno().abrirModalEdicao();
    }//GEN-LAST:event_btnEditarAlunoActionPerformed

    private void btnEditarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProfessorActionPerformed
        this.gerenciadorInterface.getProfessor().abrirModalEdicao();
    }//GEN-LAST:event_btnEditarProfessorActionPerformed

    private void btnEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpresaActionPerformed
        this.gerenciadorInterface.getEmpresa().abrirModalEdicao();
    }//GEN-LAST:event_btnEditarEmpresaActionPerformed

    private void btnAbrirProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProjetoActionPerformed
        Projeto projeto = (Projeto) this.gerenciadorInterface.getProjeto().getTableModel().getSelected();
        if(projeto != null) this.gerenciadorInterface.getProjeto().abrirProjeto(projeto);
    }//GEN-LAST:event_btnAbrirProjetoActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        this.gerenciadorInterface.getEmpresa().listar();
    }//GEN-LAST:event_jPanel4ComponentShown

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        this.gerenciadorInterface.getProfessor().listar();
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        this.gerenciadorInterface.getAluno().listar();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        if(this.carregou) this.gerenciadorInterface.getProjeto().listar();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void excluirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEmpresaActionPerformed
        this.gerenciadorInterface.getEmpresa().excluir();
    }//GEN-LAST:event_excluirEmpresaActionPerformed

    private void excluirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProfessorActionPerformed
        this.gerenciadorInterface.getProfessor().excluir();
    }//GEN-LAST:event_excluirProfessorActionPerformed

    private void excluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAlunoActionPerformed
        this.gerenciadorInterface.getAluno().excluir();
    }//GEN-LAST:event_excluirAlunoActionPerformed

    private void excluirProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProjetoActionPerformed
        this.gerenciadorInterface.getProjeto().excluir();
    }//GEN-LAST:event_excluirProjetoActionPerformed

    private void limparFiltroEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFiltroEmpresasActionPerformed
        this.gerenciadorInterface.getEmpresa().listar();
    }//GEN-LAST:event_limparFiltroEmpresasActionPerformed

    private void limparFiltroProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFiltroProfessoresActionPerformed
        this.gerenciadorInterface.getProfessor().listar();
    }//GEN-LAST:event_limparFiltroProfessoresActionPerformed

    private void limparFiltroAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFiltroAlunosActionPerformed
        this.gerenciadorInterface.getAluno().listar();
    }//GEN-LAST:event_limparFiltroAlunosActionPerformed

    private void limparFiltroProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFiltroProjetosActionPerformed
        this.gerenciadorInterface.getProjeto().listar();
    }//GEN-LAST:event_limparFiltroProjetosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirProjeto;
    private javax.swing.JButton btnEditarAluno;
    private javax.swing.JButton btnEditarEmpresa;
    private javax.swing.JButton btnEditarProfessor;
    private javax.swing.JButton btnEditarProjeto;
    private javax.swing.JButton btnFiltrarAlunos;
    private javax.swing.JButton btnFiltrarEmpresas;
    private javax.swing.JButton btnFiltrarProfessores;
    private javax.swing.JButton btnFiltrarProjetos;
    private javax.swing.JButton btnNovaEmpresa;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnNovoProfessor;
    private javax.swing.JButton btnNovoProjeto;
    private javax.swing.JScrollPane containerempresas;
    private javax.swing.JScrollPane containerprofessores;
    private javax.swing.JButton excluirAluno;
    private javax.swing.JButton excluirEmpresa;
    private javax.swing.JButton excluirProfessor;
    private javax.swing.JButton excluirProjeto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbListaAlunos;
    private javax.swing.JTable jtbListaEmpresas;
    private javax.swing.JTable jtbListaProfessores;
    private javax.swing.JTable jtbListaProjetos;
    private javax.swing.JButton limparFiltroAlunos;
    private javax.swing.JButton limparFiltroEmpresas;
    private javax.swing.JButton limparFiltroProfessores;
    private javax.swing.JButton limparFiltroProjetos;
    private javax.swing.JScrollPane listagemProjetos;
    // End of variables declaration//GEN-END:variables
}
